services:
  server:
    image: ghcr.io/joel-muller/world-quiz-server:latest
    container_name: world-quiz-server
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/world-quiz?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      MAILGUN_URL: ${MAILGUN_URL}
      MAILGUN_SENDER_EMAIL: ${MAILGUN_SENDER_EMAIL}
    expose:
      - "8080"
    depends_on:
      - mongo

  client:
    image: ghcr.io/joel-muller/world-quiz-client:latest
    container_name: world-quiz-client
    restart: unless-stopped
    expose:
      - "8080"
    depends_on:
      - server

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/world-quiz?authSource=admin
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - client
      - server

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN}
    depends_on:
      - caddy
    restart: always

volumes:
  caddy_data:
  caddy_config:
