spring.application.name=worldquiz
place.csv.base-dir=data
place.csv.first-id=10000

spring.data.mongodb.uri=${MONGO_URI}
jwt.secret=${JWT_SECRET}

mailgun.api.key=${MAILGUN_API_KEY}
mailgun.url=${MAILGUN_URL}
mailgun.sender.email=${MAILGUN_SENDER_EMAIL}

mailgun.threshold.max=${MAILGUN_LIMIT_PER_DAY}
mailgun.threshold.user=${MAILGUN_LIMIT_PER_DAY_PER_USER}
