FROM eclipse-temurin:21-jdk

RUN apt-get update
RUN apt-get install -y openssh-server git maven
RUN rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash dev && echo "dev:dev" | chpasswd
RUN mkdir -p /var/run/sshd

WORKDIR /workspace
EXPOSE 22 8080

CMD ["/usr/sbin/sshd", "-D"]
